#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
fplugctl - F-Plug Daemon

Copyright (C) 2014 SUNAGA Takahiro

This software is released under the MIT License.
http://opensource.org/licenses/mit-license.php

"""

import sys
import os, os.path
import datetime, time
import traceback

from pyfplug import *

DEFAULT_DEVICE = "/dev/rfcomm0"


if len(sys.argv) == 1 or sys.argv[1] == '-h' or sys.argv[1] == '--help':
    print """fplugctl - F-Plug Command line tool
Usage: 
    fplugctl [-d /dev/rfcommX] data-dir
    """
    sys.exit(1)


if sys.argv[1] == '-d':
    dev_fn = sys.argv[2]
    cmd = sys.argv[3:]
else:
    dev_fn = DEFAULT_DEVICE
    cmd = sys.argv[1:]


datadir = cmd[0]
curfn = cmd[1]

def get_cur():
    data = "TMP={0}\nHUM={1}\nILL={2}\nPWR={3}\n".format(
        dev.get_temperature(),
        dev.get_humidity(),
        dev.get_illuminance(),
        dev.get_power_realtime()
    )
    print "CUR DATA: ", ' '.join(data.split("\n"))
    with open(curfn, "w") as f:
        f.write(data)

def get_acc():
    power_list = dev.get_acc_power()
    if power_list is None:
        power_list = [None]
    data = ','.join(str(v) for v in list(reversed(power_list)))
    
    now = datetime.datetime.now()
    fn = 'data-{0:%Y-%m}.log'.format(now)
    line = ('{0:%d,%H,%H:%M:%S,}'.format(now)) + data + "\n"
    with open(os.path.join(datadir, fn), 'a') as f:
        f.write(line)

def get_hour():
    return "{0:%Y%m%d%H}".format(datetime.datetime.now())


dev = None
dev_init_time = None
def init_dev():
    global dev
    global dev_init_time
    dev_init_time = datetime.datetime.now()
    if dev:
        dev.close()
    dev = FPlugDevice(dev_fn, debug = False, timeout = 15, comm_wait = 0.05)


cur_hour = ""


def close_dev():
    global dev
    print "Device closed"
    if dev:
        dev.close()
        dev = None
    

while True:
    try:
        if dev:
            init_delta = datetime.datetime.now() - dev_init_time
            if init_delta > datetime.timedelta(seconds = 60 * 60 * 6):
                close_dev()

        if not dev:
            print "Device Initialized"
            init_dev()
        
        if dev:
            now_hour = get_hour()
            dev.clear_recv(timeout = 1)
            dev.led_on()
            if now_hour != cur_hour:
                get_acc()
                cur_hour = now_hour
                print "UPDATE HOUR: NOW", now_hour, " CUR:", cur_hour
            get_cur()
            time.sleep(1)
            dev.led_off()
    except Exception, e:
        print "EXCEPTION:"
        traceback.print_exc()
        close_dev()
    time.sleep(1)

